## Valid TOML config file
# data-path="~/besudata" # Path

## Network
# bootnodes=["enode://001@123:4567", "enode://002@123:4567", "enode://003@123:4567"]

p2p-host=["10.5.0.2"] 
p2p-enabled=true
p2p-port=30303
max-peers=25

rpc-http-host=["10.5.0.2"] 
rpc-http-port=8545 
rpc-http-enabled=true 
rpc-http-api=["ETH","NET","QBFT"] 

#allow all
host-allowlist=["*"] 
rpc-http-cors-origins=["*"]
#rpc-ws-host="9.10.11.12"
#rpc-ws-port=9101

# Chain
#genesis-file="~/genesis.json" # Path to the custom genesis file

# Mining
#miner-enabled=true
#miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"